#pragma once
// evaluator.h — GPU batch board evaluation
//
// Stage 3 of the pipeline:
//   cuBLAS : [N×64] board matrix × [64×4] spatial-weight matrix → feature scores
//   Kernel : per-piece piece-square table (PST) lookup via constant memory
//   cuFFT  : batch FFT on white pawn file distribution → pawn structure score
//   Thrust : parallel sort + rank assignment
//
// Evaluation is performed on the board STATE (float[64] piece values)
// generated by board_gen — not on image pixels.

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    float score;          // combined evaluation score (higher = better for white)
    float material;       // raw material balance (piece-value sum)
    float positional;     // piece-square table bonus (normalised)
    float pawn_structure; // cuFFT high-frequency pawn energy (lower = better structure)
    int   rank;           // Thrust rank among all N boards (0 = best)
    char  filename[256];  // source board PNG path
} BoardEval;

// Evaluate N boards in batch on the GPU.
//   board_states : float[N * 64] — piece values from board_to_floats(), host memory
//   filenames    : const char*[N]
//   N            : number of boards
//   results      : BoardEval[N], allocated by caller
// Returns 1 on success, 0 on failure.
int evaluator_run(
    const float  *board_states,
    const char  **filenames,
    int           N,
    BoardEval    *results);

// Write evaluation results to a CSV file (rank order).
// Returns 1 on success, 0 on failure.
int evaluator_save_csv(const char *path, const BoardEval *results, int N);

#ifdef __cplusplus
}
#endif
